In [1]:
# code replicated from https://github.com/charleywu/graphInference/blob/master/analyses/PXP.ipynb

In [4]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd 

from bms import GroupBMC #https://github.com/cpilab/group-bayesian-model-comparison

### Protected exceedance probability across all age groups

In [11]:
#Load data
m = -pd.read_csv('modelResults/pxp/nLL.csv', sep=',',  header=None).to_numpy().T
#make negative (i.e., log likelihoods from nLLs) and transpose

In [12]:
#compute pxp
result = GroupBMC(m).get_result().protected_exceedance_probability
result =  result.reshape(1, result.shape[0]) #reshape from column vector to row vector
#Save
np.savetxt('modelResults/pxp/PXP.csv', result, delimiter=',')

In [13]:
result
# GP-UCB, BMT-UCB, 'GP-GM', 'GP-EG'

array([[9.99999904e-01, 4.71278773e-14, 9.54592740e-08, 6.43033595e-10]])

### Protected exceedance probability for each age group individually

#### Age group 5-6

In [14]:
#Load data
m1 = -pd.read_csv('modelResults/pxp/nLL5-6.csv', sep=',',  header=None).to_numpy().T
#make negative (i.e., negative log likelihoods) and transpose

In [16]:
#compute pxp
result1 = GroupBMC(m1).get_result().protected_exceedance_probability
result1 =  result1.reshape(1, result1.shape[0]) #reshape from column vector to row vector
#Save
np.savetxt('modelResults/pxp/PXP5-6.csv', result1, delimiter=',')
result1

array([[0.60205257, 0.06632617, 0.06586501, 0.26575625]])

#### Age group 7-8

In [17]:
#Load data
m2 = -pd.read_csv('modelResults/pxp/nLL7-8.csv', sep=',',  header=None).to_numpy().T
#make negative (i.e., negative log likelihoods) and transpose

In [18]:
#compute pxp
result2 = GroupBMC(m2).get_result().protected_exceedance_probability
result2 =  result2.reshape(1, result2.shape[0]) #reshape from column vector to row vector
#Save
np.savetxt('modelResults/pxp/PXP7-8.csv', result2, delimiter=',')
result2

array([[9.99850765e-01, 6.89827869e-12, 1.63205928e-10, 1.49234499e-04]])

#### Age group 9-10

In [19]:
#Load data
m3 = -pd.read_csv('modelResults/pxp/nLL9-10.csv', sep=',',  header=None).to_numpy().T
#make negative (i.e., negative log likelihoods) and transpose

In [20]:
#compute pxp
result3 = GroupBMC(m3).get_result().protected_exceedance_probability
result3 =  result3.reshape(1, result3.shape[0]) #reshape from column vector to row vector
#Save
np.savetxt('modelResults/pxp/PXP9-10.csv', result3, delimiter=',')
result3

array([[9.99761141e-01, 2.07472079e-06, 2.22760086e-04, 1.40246270e-05]])

#### Age group 11-13

In [21]:
#Load data
m4 = -pd.read_csv('modelResults/pxp/nLL11-13.csv', sep=',',  header=None).to_numpy().T
#make negative (i.e., negative log likelihoods) and transpose

In [22]:
#compute pxp
result4 = GroupBMC(m4).get_result().protected_exceedance_probability
result4 =  result4.reshape(1, result4.shape[0]) #reshape from column vector to row vector
#Save
np.savetxt('modelResults/pxp/PXP11-13.csv', result4, delimiter=',')
result4

array([[9.99998446e-01, 8.64632811e-08, 1.44296876e-06, 2.44956169e-08]])

#### Age group 14-17

In [23]:
#Load data
m5 = -pd.read_csv('modelResults/pxp/nLL14-17.csv', sep=',',  header=None).to_numpy().T
#make negative (i.e., negative log likelihoods) and transpose

In [24]:
#compute pxp
result5 = GroupBMC(m5).get_result().protected_exceedance_probability
result5 =  result5.reshape(1, result5.shape[0]) #reshape from column vector to row vector
#Save
np.savetxt('modelResults/pxp/PXP14-17.csv', result5, delimiter=',')
result5

array([[9.97422736e-01, 3.39328540e-04, 1.94435520e-03, 2.93579951e-04]])

#### Age group 18-24

In [25]:
#Load data
m6 = -pd.read_csv('modelResults/pxp/nLL18-24.csv', sep=',',  header=None).to_numpy().T
#make negative (i.e., negative log likelihoods) and transpose

In [26]:
#compute pxp
result6 = GroupBMC(m6).get_result().protected_exceedance_probability
result6 =  result6.reshape(1, result6.shape[0]) #reshape from column vector to row vector
#Save
np.savetxt('modelResults/pxp/PXP18-24.csv', result6, delimiter=',')
result6

array([[9.99995766e-01, 2.97307714e-06, 1.26124434e-06, 8.75917683e-11]])

#### Age group 25-55

In [27]:
#Load data
m7 = -pd.read_csv('modelResults/pxp/nLL25-55.csv', sep=',',  header=None).to_numpy().T
#make negative (i.e., negative log likelihoods) and transpose

In [28]:
#compute pxp
result7 = GroupBMC(m7).get_result().protected_exceedance_probability
result7 =  result7.reshape(1, result7.shape[0]) #reshape from column vector to row vector
#Save
np.savetxt('modelResults/pxp/PXP25-55.csv', result7, delimiter=',')
result7

array([[9.98342945e-01, 2.26638095e-04, 1.41704377e-03, 1.33734881e-05]])